name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Cosign
        uses: sigstore/cosign-installer@main     
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          # registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.actor }}/cosign-demo
          tags: |
            type=ref,event=pr,prefix=PR-
            type=sha,prefix=SHA-
          flavor: |
            latest=false
            prefix=
            suffix=            
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Sign image with a key
        run: |
          echo "${TAGS}"
          echo "$COSIGN_KEY" > /tmp/cosign.key
          cosign sign --key /tmp/cosign.key "${TAGS}"
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
