name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: sigstore/cosign-installer@v1.3.1
        with:
          cosign-release: "v1.3.1" # optional
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.actor }}/cosign-demo
          tags: |
            type=ref,event=pr,prefix=PR-
            type=sha,prefix=SHA-
          flavor: |
            latest=false
            prefix=
            suffix=
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Sign image with a key
        run: |
          echo "$COSIGN_KEY" > /tmp/cosign.key
          echo "${TAGS}" | xargs -n 1 cosign sign --key /tmp/cosign.key
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
