name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.actor }}/cosign-demo
          tags: |
            type=ref,event=pr,prefix=PR-
            type=sha,prefix=SHA-
          flavor: |
            latest=false
            prefix=
            suffix=            
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
      - name: Install Cosign
        uses: sigstore/cosign-installer@v1.3.0
        with:
          cosign-release: 'v1.3.0'
      - name: Check install!
        run: cosign version
